name: CI
on: pull_request

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        poetry-version: ["1.1.14"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Virtual environment info
        run: poetry env info
      - name: Run flake8 (along with black, isort and bandit wrapper)
        run: poetry run flake8 src tests
      - name: Run mypy
        run: poetry run mypy --install-types --non-interactive --ignore-missing-imports src
      - name: Run pytest
        run: poetry run pytest