name: CD
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
        with:
          python-version: "3.13"
          enable-cache: true
      - name: Bump version
        run: uv version "$TAG_NAME"
        env:
          TAG_NAME: ${{ github.ref_name }}
      - name: Build
        run: uv build
      - name: Publish to PyPI
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
