name: CD
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
          enable-cache: true
      - name: Bump version
        run: uv version ${{github.ref_name}}
      - name: Build
        run: uv build
      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
